Repository Leo-Corporation/Passliss, pull requests merged in 2022-11, with the labels that each got.

#199 Version 2.7.0.2211
  Passliss.Setup/Setup.iss
  Passliss/Classes/Global.cs
  Passliss/Classes/PasswordConfigurationManager.cs
  Passliss/Classes/Settings.cs
  Passliss/MainWindow.xaml
  Passliss/MainWindow.xaml.cs
  Passliss/Pages/EncryptPage.xaml.cs
  Passliss/Pages/GeneratePage.xaml
  Passliss/Pages/GeneratePage.xaml.cs
  Passliss/Pages/SettingsPage.xaml
  Passliss/Pages/SettingsPage.xaml.cs
  Passliss/Pages/StrenghtPage.xaml
  Passliss/Pages/StrenghtPage.xaml.cs
  Passliss/Passliss.csproj
  Passliss/Properties/Resources.Designer.cs
  Passliss/Properties/Resources.en-US.resx
  Passliss/Properties/Resources.fr-FR.resx
  Passliss/Properties/Resources.resx
  Passliss/Properties/Resources.zh-CN.resx
  Passliss/UserControls/PasswordConfigurationItem.xaml
  Passliss/UserControls/PasswordConfigurationItem.xaml.cs
  Passliss/Windows/LoadPasswordConfigurationWindow.xaml
  Passliss/Windows/LoadPasswordConfigurationWindow.xaml.cs
  Passliss/Windows/NewPasswordConfigurationWindow.xaml
  Passliss/Windows/NewPasswordConfigurationWindow.xaml.cs
  Passliss/Windows/SeeFullPassword.xaml.cs
Labels: enhancement, roadmap, vNext

#201 Updated Simplified Chinese translation
  Passliss/Properties/Resources.zh-CN.resx
Labels: translation, vNext

#202 Version 2.7.1.2211
  Passliss.Setup/Setup.iss
  Passliss/Classes/Global.cs
  Passliss/Passliss.csproj
  Passliss/Properties/Resources.zh-CN.resx
Labels: enhancement, translation, vNext
