Repository Leo-Corporation/Passliss, pull requests merged in 2022-01, with the labels that each got.

#113 Update license copyright year(s)
  LICENSE
Labels: documentation

#120 Add Simplified Chinese translation
  Passliss/Properties/Resources.zh-CN.resx
Labels: enhancement, translation, vNext

#124 Version 2.1.0.2201
  Passliss.Setup/Setup.iss
  Passliss/Classes/Global.cs
  Passliss/Classes/Settings.cs
  Passliss/MainWindow.xaml.cs
  Passliss/Pages/EncryptPage.xaml
  Passliss/Pages/GeneratePage.xaml
  Passliss/Pages/GeneratePage.xaml.cs
  Passliss/Pages/SettingsPage.xaml
  Passliss/Pages/SettingsPage.xaml.cs
  Passliss/Passliss.csproj
  Passliss/Properties/Resources.Designer.cs
  Passliss/Properties/Resources.en-US.resx
  Passliss/Properties/Resources.fr-FR.resx
  Passliss/Properties/Resources.resx
  Passliss/Properties/Resources.zh-CN.resx
Labels: enhancement, roadmap, vNext
