Repository Leo-Corporation/Passliss, pull requests merged in 2022-06, with the labels that each got.

#170 Version 2.5.0.2206
  Passliss.Setup/Setup.iss
  Passliss/App.xaml
  Passliss/App.xaml.cs
  Passliss/Classes/Global.cs
  Passliss/Classes/Settings.cs
  Passliss/MainWindow.xaml.cs
  Passliss/Pages/GeneratePage.xaml
  Passliss/Pages/GeneratePage.xaml.cs
  Passliss/Pages/SettingsPage.xaml
  Passliss/Pages/SettingsPage.xaml.cs
  Passliss/Pages/StrenghtPage.xaml
  Passliss/Passliss.csproj
  Passliss/Properties/Resources.Designer.cs
  Passliss/Properties/Resources.en-US.resx
  Passliss/Properties/Resources.fr-FR.resx
  Passliss/Properties/Resources.resx
  Passliss/Properties/Resources.zh-CN.resx
Labels: enhancement, roadmap, vNext

#172 Updated Simplified Chinese translation
  Passliss/Properties/Resources.zh-CN.resx
Labels: translation, roadmap, vNext

#173 Version 2.5.1.2206
  Passliss.Setup/Setup.iss
  Passliss/Classes/Global.cs
  Passliss/MainWindow.xaml.cs
  Passliss/Pages/GeneratePage.xaml.cs
  Passliss/Pages/SettingsPage.xaml.cs
  Passliss/Passliss.csproj
  Passliss/Properties/Resources.zh-CN.resx
  Xalyus Updater/AssemblyInfo.cs
  Xalyus Updater/MainWindow.xaml.cs
Labels: translation, vNext
